Remove use of specific atom class and use generic atom instead
radixdlt/radix-engine-library pull request #17
Opened 2020-05-11 12:57 UTC by talekhinezh

* RE should only be responsible for RE level logic so use interface rather than class to retrieve required RE data

2020-05-11 15:21 UTC, flotothemoon commented on src/main/java/com/radixdlt/engine/RadixEngineAtom.java
> + * Radix Engine interface for retrieving a sequence of instruction to
instructions

2020-05-11 15:24 UTC, flotothemoon approved these changes
Fine by me

2020-05-12 08:25 UTC, clstrfsck requested changes
The missing type argument needs fixing in RadixEngineTest, and would prefer to see unused logger removed also.

2020-05-12 08:25 UTC, clstrfsck commented on src/test/java/com/radixdlt/engine/RadixEngineTest.java
>  		EngineStore engineStore = mock(EngineStore.class);
EngineStore missing a type argument, which causes Eclipse compiler to type-fail on RadixEngine construction below.

2020-05-12 08:25 UTC, clstrfsck commented on src/main/java/com/radixdlt/engine/RadixEngine.java
>  	private static final Logger log = LogManager.getLogger(RadixEngine.class);
No longer used -> remove.

2020-05-12 12:48 UTC, clstrfsck approved these changes

2020-05-12 12:49 UTC, merged